# Generated by Django 4.2.7 on 2026-04-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.CharField(blank=True, default="Hey there! I'm using Chat App", max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images/'),
        ),
    ]
