# Generated by Django 4.2.7 on 2026-04-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='app_message_sender__a104cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='app_message_timesta_972acd_idx',
        ),
    ]
