# Generated by Django 4.2.7 on 2026-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message_deleted_at_message_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('view_employee', 'Viewed Employee Dashboard'), ('view_chat', 'Viewed Chat'), ('create_group', 'Created Group'), ('add_member', 'Added Member to Group'), ('remove_member', 'Removed Member from Group'), ('exit_view', 'Exited Employee View')], max_length=50),
        ),
    ]
