# Generated by Django 4.2.7 on 2026-04-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_adminactivitylog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
