# Generated by Django 4.2.7 on 2026-04-09 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_broadcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('dnd', 'Do Not Disturb'), ('meeting', 'In a Meeting')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='app.message'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction',
            field=models.CharField(choices=[('ok', '👍 OK'), ('not_ok', '👎 Not OK'), ('love', '❤️ Love'), ('laugh', '😂 Laugh'), ('wow', '😮 Wow'), ('sad', '😢 Sad')], max_length=10),
        ),
    ]
