# Generated by Django 4.2.7 on 2026-04-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_chatgroup_is_broadcast_employee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='app.employee'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_messages', to='app.employee'),
        ),
    ]
