# Generated by Django 4.2.7 on 2026-04-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_employee_blocked_users_message_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
