# Generated by Django 4.2.7 on 2026-04-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_employee_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_thread_reply',
            field=models.BooleanField(default=False),
        ),
    ]
