# Generated by Django 4.2.7 on 2026-04-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_message_is_thread_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='app.poll')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('view_employee', 'Viewed Employee Dashboard'), ('view_chat', 'Viewed Chat'), ('create_group', 'Created Group'), ('add_member', 'Added Member to Group'), ('remove_member', 'Removed Member from Group'), ('exit_view', 'Exited Employee View'), ('pin_message', 'Pinned/Unpinned Message')], max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('meet', 'Google Meet'), ('poll', 'Poll')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='poll',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='app.message'),
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to='app.employee')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='app.polloption')),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('option', 'employee')},
            },
        ),
    ]
