# Generated by Django 4.2.7 on 2026-04-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_poll_polloption_alter_adminactivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text='Stored for admin reference. Auto-synced with Django auth.', max_length=128),
        ),
    ]
