# Generated by Django 4.2.7 on 2026-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_employee_plain_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='plain_password',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
