# Generated by Django 4.2.7 on 2026-04-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_employee_plain_password_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='allowed_chatters',
            field=models.ManyToManyField(blank=True, help_text="Employees allowed to chat when permission is 'selected'", related_name='allowed_chat_groups', to='app.employee'),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='chat_permission',
            field=models.CharField(choices=[('all', 'All Members Can Chat'), ('selected', 'Only Selected Members Can Chat'), ('admins_only', 'Only Admins Can Chat')], default='all', help_text='Controls who can send messages in this group', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminactivitylog',
            name='action',
            field=models.CharField(choices=[('view_employee', 'Viewed Employee Dashboard'), ('view_chat', 'Viewed Chat'), ('create_group', 'Created Group'), ('add_member', 'Added Member to Group'), ('remove_member', 'Removed Member from Group'), ('exit_view', 'Exited Employee View'), ('pin_message', 'Pinned/Unpinned Message'), ('change_chat_permission', 'Changed Group Chat Permission')], max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('meet', 'Google Meet'), ('poll', 'Poll'), ('system', 'System')], default='text', max_length=10),
        ),
    ]
