# Generated by Django 4.2.7 on 2026-04-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_chatgroup_allowed_chatters_chatgroup_chat_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
