# Generated by Django 4.2.7 on 2026-04-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_employee_is_online_employee_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
